version: 0.2

phases:
  pre_build:
    commands:
      - echo Validating environment...
      - [ -n "${AWS_DEFAULT_REGION}" ] || ( echo "Missing AWS_DEFAULT_REGION" ; exit 1)
      - [ -n "${AWS_ACCOUNT_ID}" ]     || ( echo "Missing AWS_ACCOUNT_ID" ; exit 1)
      - [ -n "${IMAGE_NAME}" ]         || ( echo "Missing IMAGE_NAME" ; exit 1)
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - ./hooks/build
      - ./hooks/test
      - source ./hooks/env
      - docker tag $IMAGE_NAME:$SOURCE_BRANCH $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$SOURCE_BRANCH      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$SOURCE_BRANCH
