#!/bin/bash -xe

. ./hooks/env

# Download Kubernetes images and store in context
K3S_IMAGES="
docker.io/coredns/coredns:1.3.0
docker.io/library/traefik:1.7.9
docker.io/rancher/klipper-helm:v0.1.3
docker.io/rancher/klipper-helm:v0.1.2
docker.io/rancher/klipper-lb:v0.1.1
k8s.gcr.io/pause:3.1
rancher/local-path-provisioner:v0.0.4
"

K3S_IMAGES="${K3S_IMAGES} gcr.io/kubernetes-helm/tiller:v${HELM_VERSION}"

K3S_TARBALL="k3s-${K3S_VERSION}-${HELM_VERSION}.tar.gz"
if [ ! -f "${K3S_TARBALL}" ]; then
    for I in ${K3S_IMAGES}; do docker image inspect $I >/dev/null 2>/dev/null || docker pull $I; done
    docker save ${K3S_IMAGES} | gzip -9 > "${K3S_TARBALL}"
fi

docker build \
    --build-arg "SOURCE_COMMIT=${GIT_SHA1}" \
    --build-arg "DOCKERFILE_PATH=${DOCKERFILE_PATH}" \
    --build-arg "SOURCE_TYPE=${SOURCE_TYPE}" \
    --build-arg "HELM_VERSION=${HELM_VERSION}" \
    --build-arg "K3S_VERSION=${K3S_VERSION}" \
    ${APT_PROXY:+--build-arg "APT_PROXY=${APT_PROXY}"} \
    -t ${IMAGE_NAME} .
